koe/concesionaria/urls.py
from django.urls import include, path, re_path
from django.contrib.auth.decorators import login_required

from . import views
app_name = "concesionaria"

urlpatterns = [
                path('tablon', login_required(views.Tablon), name='tablon'),


                path('nuevapersona', login_required(views.NuevaPersona.as_view()), name='nueva_persona'),
                path('listapersona', login_required(views.ListaPersona.as_view()), name='lista_persona'),
                re_path(r'^editarpersona/(?P<pk>\d+)/$', login_required(views.EditarPersona.as_view()), name='editar_persona'),
                re_path(r'^eliminarpersona/(?P<pk>\d+)/$', login_required(views.EliminarPersona.as_view()), name='eliminar_persona'),

                path('nuevadocumentacion', login_required(views.NuevaDocumentacion.as_view()), name='nueva_documentacion'),
                path('listadocumentacion', login_required(views.ListaDocumentacion.as_view()), name='lista_documentacion'),
                re_path(r'^editardocumentacion/(?P<pk>\d+)/$', login_required(views.EditarDocumentacion.as_view()), name='editar_documentacion'),
                re_path(r'^eliminardocumentacion/(?P<pk>\d+)/$', login_required(views.EliminarDocumentacion.as_view()), name='eliminar_documentacion'),

                path('nuevarelacion', login_required(views.NuevaRelacion.as_view()), name='nueva_relacion'),
                path('listarelacion', login_required(views.ListaRelacion.as_view()), name='lista_relacion'),
                re_path(r'^editarrelacion/(?P<pk>\d+)/$', login_required(views.EditarRelacion.as_view()), name='editar_relacion'),
                re_path(r'^eliminarrelacion/(?P<pk>\d+)/$', login_required(views.EliminarRelacion.as_view()), name='eliminar_relacion'),

                path('nuevacategoria', login_required(views.NuevaCategoria.as_view()), name='nueva_categoria'),
                path('listacategoria', login_required(views.ListaCategoria.as_view()), name='lista_categoria'),
                re_path(r'^editarcategoria/(?P<pk>\d+)/$', login_required(views.EditarCategoria.as_view()), name='editar_categoria'),
                re_path(r'^eliminarcategoria/(?P<pk>\d+)/$', login_required(views.EliminarCategoria.as_view()), name='eliminar_categoria'),

                path('nuevamarca', login_required(views.NuevaMarca.as_view()), name='nueva_marca'),
                path('listamarca', login_required(views.ListaMarca.as_view()), name='lista_marca'),
                re_path(r'^editarmarca/(?P<pk>\d+)/$', login_required(views.EditarMarca.as_view()), name='editar_marca'),
                re_path(r'^eliminarmarca/(?P<pk>\d+)/$', login_required(views.EliminarMarca.as_view()), name='eliminar_marca'),

                path('nuevoestadocivil', login_required(views.NuevoEstadoCivil.as_view()), name='nuevo_estadocivil'),
                path('listaestadocivil', login_required(views.ListaEstadoCivil.as_view()), name='lista_estadocivil'),
                re_path(r'^editarestadocivil/(?P<pk>\d+)/$', login_required(views.EditarEstadoCivil.as_view()), name='editar_estadocivil'),
                re_path(r'^eliminarestadocivil/(?P<pk>\d+)/$', login_required(views.EliminarEstadoCivil.as_view()), name='eliminar_estadocivil'),

                path('nuevocolor', login_required(views.NuevoColor.as_view()), name='nuevo_color'),
                path('listacolor', login_required(views.ListaColor.as_view()), name='lista_color'),
                re_path(r'^editarcolor/(?P<pk>\d+)/$', login_required(views.EditarColor.as_view()), name='editar_color'),
                re_path(r'^eliminarcolor/(?P<pk>\d+)/$', login_required(views.EliminarColor.as_view()), name='eliminar_color'),

                path('nuevaformapago', login_required(views.NuevaFormaPago.as_view()), name='nueva_formapago'),
                path('listaformapago', login_required(views.ListaFormaPago.as_view()), name='lista_formapago'),
                re_path(r'^editarformapago/(?P<pk>\d+)/$', login_required(views.EditarFormaPago.as_view()), name='editar_formapago'),
                re_path(r'^eliminarformapago/(?P<pk>\d+)/$', login_required(views.EliminarFormaPago.as_view()), name='eliminar_formapago'),



                path('nuevotipomotor', login_required(views.NuevoTipoMotor.as_view()), name='nuevo_tipomotor'),
                path('listatipomotor', login_required(views.ListaTipoMotor.as_view()), name='lista_tipomotor'),
                re_path(r'^editartipomotor/(?P<pk>\d+)/$', login_required(views.EditarTipoMotor.as_view()), name='editar_tipomotor'),
                re_path(r'^eliminartipomotor/(?P<pk>\d+)/$', login_required(views.EliminarTipoMotor.as_view()), name='eliminar_tipomotor'),

                path('nuevogasto', login_required(views.NuevoGasto.as_view()), name='nuevo_gasto'),
                path('listagasto', login_required(views.ListaGasto.as_view()), name='lista_gasto'),
                re_path(r'^editargasto/(?P<pk>\d+)/$', login_required(views.EditarGasto.as_view()), name='editar_gasto'),
                re_path(r'^eliminargasto/(?P<pk>\d+)/$', login_required(views.EliminarGasto.as_view()), name='eliminar_gasto'),

                path('nuevorodado', login_required(views.NuevoRodado.as_view()), name='nuevo_rodado'),
                path('listarodado', login_required(views.ListaRodado.as_view()), name='lista_rodado'),
                re_path(r'^editarrodado/(?P<pk>\d+)/$', login_required(views.EditarRodado.as_view()), name='editar_rodado'),
                re_path(r'^eliminarrodado/(?P<pk>\d+)/$', login_required(views.EliminarRodado.as_view()), name='eliminar_rodado'),

                path('nuevaventa', login_required(views.NuevaVenta.as_view()), name='nueva_venta'),
                path('listaventa', login_required(views.ListaVenta.as_view()), name='lista_venta'),

                path('nuevadocumentacionrodado', login_required(views.NuevaDocumentacionRodado.as_view()), name='nueva_documentacionrodado'),
                path('listadocumentacionrodado', login_required(views.ListaDocumentacionRodado.as_view()), name='lista_documentacionrodado'),

                path('nuevogastorodado', login_required(views.NuevoGastoRodado.as_view()), name='nuevo_gastorodado'),
                path('listagastorodado', login_required(views.ListaGastoRodado.as_view()), name='lista_gastorodado'),
                re_path(r'^editargastorodado/(?P<id_gastorodado>\d+)/$', login_required(views.EditarGastoRodado), name='editar_gastorodado'),


                path('disponibles', login_required(views.Disponibles), name='lista_disponibles'),
                path('estadorodado/<int:id_rodado>/', login_required(views.EstadoRodado), name='estado_rodado'),

                path('confirmarboleto/<int:id_rodado>/', login_required(views.ConfirmarBoleto), name='confirmar_boleto'),

                path('nuevacaja', login_required(views.NuevaCaja.as_view()), name='nueva_caja'),
                path('listacaja', login_required(views.ListaCaja.as_view()), name='lista_caja'),
                re_path(r'^editarcaja/(?P<pk>\d+)/$', login_required(views.EditarCaja.as_view()), name='editar_caja'),

                #path('nuevacobranzatransferencia', login_required(views.NuevaCobranzaTransferencia.as_view()), name='nueva_cobranzatransferencia'),
                path('listacobranzatransferencia', login_required(views.ListaCobranzaTransferencia), name='lista_cobranzatransferencia'),
                #re_path(r'^editarcobranzatransferencia/(?P<pk>\d+)/$', login_required(views.EditarCobranzaTransferencia.as_view()), name='editar_cobranzatransferencia'),
                #re_path(r'^eliminarcobranzatransferencia/(?P<pk>\d+)/$', login_required(views.EliminarCobranzaTransferencia.as_view()), name='eliminar_cobranzatransferencia'),



]

koe/koe/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

#estos imports es para el manejo de las imgs
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('concesionaria/', include('concesionaria.urls', namespace = "concesionaria")),
    path('usuarios/', include('usuarios.urls', namespace= "usuarios")),
    path('', LoginView.as_view(template_name='index.html'), name = "login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset/password_reset', PasswordResetView.as_view(template_name='registration/password_reset_form.html', email_template_name='registration/password_reset_email.html'), name = 'password_reset'),
    path('reset/password_reset_done', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name = 'password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-za-z_\-]+)/(?P<token>.+)/$', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name = 'password_reset_confirm'),
    path('reset/done',PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html') , name = 'password_reset_complete'),
]

urlpatterns += static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

koe/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">

    <!-- Cargo CSS de BS local -->
   <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
   <link rel="stylesheet" href="{% static 'bootstrap/css/icons.css' %}">
   <script src="{% static 'bootstrap/js/jquery-3.5.1.js' %}"></script>
   <script src="{% static 'bootstrap/js/popper.min.js' %}"></script>
   <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

    <title> {% block title %}Koe - Concesionarias{% endblock %}</title>


  </head>
  <body>
    <div class="container-fluid">

      {% block encabezado %}

        <div class="container-fluid bg-dark">
          <h6 style="color:white;">Empresa: Concesionaria Cemar | Victoria | Entre Ríos</h6>
        </div>
        <nav class="navbar navbar-dark navbar-expand-lg bg-dark">
          <a class="navbar-brand" href="#">Koe - Concesionarias<span class="badge badge-secondary">v1.0</span></a>
          <!-- DEPRECATED
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        -->


          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'concesionaria:tablon' %}">Inicio <span class="sr-only">Inicio</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'concesionaria:lista_persona' %}">Personas</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Rodados
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'concesionaria:lista_rodado' %}">Ingresos</a>
                  <a class="dropdown-item" href="{% url 'concesionaria:lista_venta' %}">Ventas</a>
                  <a class="dropdown-item" href="{% url 'concesionaria:lista_documentacionrodado' %}">Documentación rodado</a>
                  <a class="dropdown-item" href="{% url 'concesionaria:lista_gastorodado' %}">Gasto rodado</a>

                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'concesionaria:lista_disponibles' %}">Disponibles</a>
                </div>

              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Administración
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'concesionaria:lista_cobranzatransferencia' %}">Cobranza transferencia</a>
                </div>

              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Configuración
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'concesionaria:lista_documentacion' %}">Documentación</a>
                  <a class="dropdown-item" href="{% url 'concesionaria:lista_categoria' %}">Categorías rodados</a>
                  <a class="dropdown-item" href="{% url 'concesionaria:lista_relacion' %}">Relaciones frente a IVA</a>
                  <a class="dropdown-item" href="{% url 'concesionaria:lista_gasto' %}">Conceptos de gastos</a>
                  <!--
                  NO IMPLEMENTADO
                  <a class="dropdown-item" href="{% url 'concesionaria:lista_formapago' %}">Formas de pago</a>
                -->
                  <a class="dropdown-item" href="{% url 'concesionaria:lista_marca' %}">Marcas</a>
                  <a class="dropdown-item" href="{% url 'concesionaria:lista_tipomotor' %}">Tipos de motores</a>
                  <a class="dropdown-item" href="{% url 'concesionaria:lista_color' %}">Colores</a>
                  <a class="dropdown-item" href="{% url 'concesionaria:lista_estadocivil' %}">Estados civiles</a>

                    <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'concesionaria:lista_caja' %}">Cajas</a>
                </div>

              </li>



              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Sistema
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'logout' %}"><i class="gg-log-off"></i>Cerrar sesión</a>
                </div>
              </li>
            </ul>
          </div>
          <button type="button" class="btn btn-danger">
              Transferencias pendientes <span class="badge badge-light">4</span>
          </button>
        </nav>


        </div>

      {% endblock %}

      {% block contenido %}

      {% endblock %}


      {% block pie %}
      <footer style="text-align:right; color:grey; margin-right:50px;">
        <p>Koe - Concesionarias<br>
        Desarrollado por Delfor Hernán Castro</p>
      </footer>
      {% endblock %}

    </div>


    <script>
    $(document).ready(function(){
      $("#busqueda").on("keyup", function() {
        var value = $(this).val().toLowerCase();
        $("#tabla tr").filter(function() {
          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
      });
    });
    </script>

  </body>
</html>