koe/concesionaria/urls.py
from django.urls import include, path, re_path
from django.contrib.auth.decorators import login_required

from . import views
app_name = "concesionaria"

urlpatterns = [
                path('tablon', login_required(views.Tablon), name='tablon'),


                path('nuevapersona', login_required(views.NuevaPersona.as_view()), name='nueva_persona'),
                path('listapersona', login_required(views.ListaPersona.as_view()), name='lista_persona'),
                re_path(r'^editarpersona/(?P<pk>\d+)/$', login_required(views.EditarPersona.as_view()), name='editar_persona'),
                re_path(r'^eliminarpersona/(?P<pk>\d+)/$', login_required(views.EliminarPersona.as_view()), name='eliminar_persona'),

                path('nuevadocumentacion', login_required(views.NuevaDocumentacion.as_view()), name='nueva_documentacion'),
                path('listadocumentacion', login_required(views.ListaDocumentacion.as_view()), name='lista_documentacion'),
                re_path(r'^editardocumentacion/(?P<pk>\d+)/$', login_required(views.EditarDocumentacion.as_view()), name='editar_documentacion'),
                re_path(r'^eliminardocumentacion/(?P<pk>\d+)/$', login_required(views.EliminarDocumentacion.as_view()), name='eliminar_documentacion'),

                path('nuevarelacion', login_required(views.NuevaRelacion.as_view()), name='nueva_relacion'),
                path('listarelacion', login_required(views.ListaRelacion.as_view()), name='lista_relacion'),
                re_path(r'^editarrelacion/(?P<pk>\d+)/$', login_required(views.EditarRelacion.as_view()), name='editar_relacion'),
                re_path(r'^eliminarrelacion/(?P<pk>\d+)/$', login_required(views.EliminarRelacion.as_view()), name='eliminar_relacion'),

                path('nuevacategoria', login_required(views.NuevaCategoria.as_view()), name='nueva_categoria'),
                path('listacategoria', login_required(views.ListaCategoria.as_view()), name='lista_categoria'),
                re_path(r'^editarcategoria/(?P<pk>\d+)/$', login_required(views.EditarCategoria.as_view()), name='editar_categoria'),
                re_path(r'^eliminarcategoria/(?P<pk>\d+)/$', login_required(views.EliminarCategoria.as_view()), name='eliminar_categoria'),

                path('nuevamarca', login_required(views.NuevaMarca.as_view()), name='nueva_marca'),
                path('listamarca', login_required(views.ListaMarca.as_view()), name='lista_marca'),
                re_path(r'^editarmarca/(?P<pk>\d+)/$', login_required(views.EditarMarca.as_view()), name='editar_marca'),
                re_path(r'^eliminarmarca/(?P<pk>\d+)/$', login_required(views.EliminarMarca.as_view()), name='eliminar_marca'),

                path('nuevoestadocivil', login_required(views.NuevoEstadoCivil.as_view()), name='nuevo_estadocivil'),
                path('listaestadocivil', login_required(views.ListaEstadoCivil.as_view()), name='lista_estadocivil'),
                re_path(r'^editarestadocivil/(?P<pk>\d+)/$', login_required(views.EditarEstadoCivil.as_view()), name='editar_estadocivil'),
                re_path(r'^eliminarestadocivil/(?P<pk>\d+)/$', login_required(views.EliminarEstadoCivil.as_view()), name='eliminar_estadocivil'),

                path('nuevocolor', login_required(views.NuevoColor.as_view()), name='nuevo_color'),
                path('listacolor', login_required(views.ListaColor.as_view()), name='lista_color'),
                re_path(r'^editarcolor/(?P<pk>\d+)/$', login_required(views.EditarColor.as_view()), name='editar_color'),
                re_path(r'^eliminarcolor/(?P<pk>\d+)/$', login_required(views.EliminarColor.as_view()), name='eliminar_color'),

                path('nuevaformapago', login_required(views.NuevaFormaPago.as_view()), name='nueva_formapago'),
                path('listaformapago', login_required(views.ListaFormaPago.as_view()), name='lista_formapago'),
                re_path(r'^editarformapago/(?P<pk>\d+)/$', login_required(views.EditarFormaPago.as_view()), name='editar_formapago'),
                re_path(r'^eliminarformapago/(?P<pk>\d+)/$', login_required(views.EliminarFormaPago.as_view()), name='eliminar_formapago'),



                path('nuevotipomotor', login_required(views.NuevoTipoMotor.as_view()), name='nuevo_tipomotor'),
                path('listatipomotor', login_required(views.ListaTipoMotor.as_view()), name='lista_tipomotor'),
                re_path(r'^editartipomotor/(?P<pk>\d+)/$', login_required(views.EditarTipoMotor.as_view()), name='editar_tipomotor'),
                re_path(r'^eliminartipomotor/(?P<pk>\d+)/$', login_required(views.EliminarTipoMotor.as_view()), name='eliminar_tipomotor'),

                path('nuevogasto', login_required(views.NuevoGasto.as_view()), name='nuevo_gasto'),
                path('listagasto', login_required(views.ListaGasto.as_view()), name='lista_gasto'),
                re_path(r'^editargasto/(?P<pk>\d+)/$', login_required(views.EditarGasto.as_view()), name='editar_gasto'),
                re_path(r'^eliminargasto/(?P<pk>\d+)/$', login_required(views.EliminarGasto.as_view()), name='eliminar_gasto'),

                path('nuevorodado', login_required(views.NuevoRodado.as_view()), name='nuevo_rodado'),
                path('listarodado', login_required(views.ListaRodado.as_view()), name='lista_rodado'),
                re_path(r'^editarrodado/(?P<pk>\d+)/$', login_required(views.EditarRodado.as_view()), name='editar_rodado'),
                re_path(r'^eliminarrodado/(?P<pk>\d+)/$', login_required(views.EliminarRodado.as_view()), name='eliminar_rodado'),

                path('nuevaventa', login_required(views.NuevaVenta.as_view()), name='nueva_venta'),
                path('listaventa', login_required(views.ListaVenta.as_view()), name='lista_venta'),

                path('nuevadocumentacionrodado', login_required(views.NuevaDocumentacionRodado.as_view()), name='nueva_documentacionrodado'),
                path('listadocumentacionrodado', login_required(views.ListaDocumentacionRodado.as_view()), name='lista_documentacionrodado'),

                path('nuevogastorodado', login_required(views.NuevoGastoRodado.as_view()), name='nuevo_gastorodado'),
                path('listagastorodado', login_required(views.ListaGastoRodado.as_view()), name='lista_gastorodado'),
                re_path(r'^editargastorodado/(?P<id_gastorodado>\d+)/$', login_required(views.EditarGastoRodado), name='editar_gastorodado'),


                path('disponibles', login_required(views.Disponibles), name='lista_disponibles'),
                path('estadorodado/<int:id_rodado>/', login_required(views.EstadoRodado), name='estado_rodado'),

                path('confirmarboleto/<int:id_rodado>/', login_required(views.ConfirmarBoleto), name='confirmar_boleto'),

                path('nuevacaja', login_required(views.NuevaCaja.as_view()), name='nueva_caja'),
                path('listacaja', login_required(views.ListaCaja.as_view()), name='lista_caja'),
                re_path(r'^editarcaja/(?P<pk>\d+)/$', login_required(views.EditarCaja.as_view()), name='editar_caja'),

                #path('nuevacobranzatransferencia', login_required(views.NuevaCobranzaTransferencia.as_view()), name='nueva_cobranzatransferencia'),
                path('listacobranzatransferencia', login_required(views.ListaCobranzaTransferencia), name='lista_cobranzatransferencia'),
                #re_path(r'^editarcobranzatransferencia/(?P<pk>\d+)/$', login_required(views.EditarCobranzaTransferencia.as_view()), name='editar_cobranzatransferencia'),
                #re_path(r'^eliminarcobranzatransferencia/(?P<pk>\d+)/$', login_required(views.EliminarCobranzaTransferencia.as_view()), name='eliminar_cobranzatransferencia'),



]

koe/koe/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

#estos imports es para el manejo de las imgs
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('concesionaria/', include('concesionaria.urls', namespace = "concesionaria")),
    path('usuarios/', include('usuarios.urls', namespace= "usuarios")),
    path('', LoginView.as_view(template_name='index.html'), name = "login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset/password_reset', PasswordResetView.as_view(template_name='registration/password_reset_form.html', email_template_name='registration/password_reset_email.html'), name = 'password_reset'),
    path('reset/password_reset_done', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name = 'password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-za-z_\-]+)/(?P<token>.+)/$', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name = 'password_reset_confirm'),
    path('reset/done',PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html') , name = 'password_reset_complete'),
]

urlpatterns += static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

koe/concesionaria/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
#LISTO EL CRUD
class RelacionIva (models.Model):
    denominacion = models.CharField(max_length=200)
    def __str__(self):
        return self.denominacion

class EstadoCivil (models.Model):

    denominacion = models.CharField(max_length=150)

    def __str__(self):
        return self.denominacion

class Persona (models.Model):
    #Esta clase representa a las personas, pueden ser vendedores o compradores
    #LISTO EL CRUD
    denominacion = models.CharField(max_length=200)
    domicilio = models.CharField(max_length=150, null=True, blank=True)
    telefono = models.CharField(max_length=40, blank=True)
    telefono2 = models.CharField(max_length=40, blank=True)
    estadoCivil = models.ForeignKey(EstadoCivil, on_delete=models.SET_NULL, null=True, blank=True)
    email = models.EmailField(max_length=150)
    provincia = models.CharField(max_length=100, blank=True, null=True)
    localidad = models.CharField(max_length=150, blank=True, null=True)
    #nro_impositivo está pensado para almacenar un número
    #de identificación tributaria, como CUIT en Argentina.
    nro_impositivo = models.CharField(max_length=20, null=True, blank=True)

    identidad = models.IntegerField(unique=True, blank=True, null=True) #DNI ÚNICO
    creado = models.DateTimeField(auto_now_add=True)
    relacionIva = models.ForeignKey(RelacionIva,on_delete=models.SET_NULL, null=True)

    fecha_record = models.DateField(auto_now_add=True, blank=True, null=True)
    user_record = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.denominacion


class CategoriaRodado (models.Model):
    #LISTO EL CRUD
    denominacion = models.CharField(max_length=70)

    def __str__(self):
        return self.denominacion

class Documentacion (models.Model):
    #LISTO EL CRUD
    denominacion = models.CharField(max_length=150)
    esObligatorio = models.BooleanField(null=True, blank=True)
    def __str__(self):
        return self.denominacion

class Marca (models.Model):
    #LISTO EL CRUD
    denominacion = models.CharField(max_length=150)

    def __str__(self):
        return self.denominacion



class TipoMotor (models.Model):
    denominacion = models.CharField(max_length=100)

    def __str__(self):
        return self.denominacion

class FormaPago (models.Model):
    denominacion = models.CharField(max_length=100)

    def __str__(self):
        return self.denominacion

class Color (models.Model):
    #LISTO EL CRUD
    denominacion = models.CharField(max_length=150)

    def __str__(self):
        return self.denominacion


class Gasto (models.Model):
    denominacion = models.CharField(max_length=150)

    def __str__(self):
        return self.denominacion


class Caja (models.Model):
    denominacion = models.CharField(max_length=150)

    def __str__(self):
        return self.denominacion


class Rodado (models.Model):
    #Esta clase representa a los rodados que se comercializan
    categoria = models.ForeignKey(CategoriaRodado, on_delete=models.SET_NULL, null=True)
    denominacion = models.CharField(max_length=200)
    modelo = models.IntegerField(blank=True, null=True)
    notas = models.CharField (max_length=200, blank=True, null=True)
    patente = models.CharField(max_length=20)
    motor = models.CharField(max_length=100, blank=True, null=True)
    chasis = models.CharField(max_length=100, blank=True, null=True)
    marca = models.ForeignKey(Marca,on_delete=models.SET_NULL, null=True)
    color = models.ForeignKey(Color,on_delete=models.SET_NULL, null=True)
    tipomotor = models.ForeignKey(TipoMotor, on_delete=models.SET_NULL, null=True, blank=True)
    imagen = models.ImageField(null=True, blank=True, upload_to="images/")
    fecha_record = models.DateField(auto_now_add=True, blank=True, null=True)
    user_record = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    #status puede ser: 1= en stock, 2=vendido
    status = models.IntegerField(default=1)

    def __str__(self):
        return self.marca.denominacion + " " + self.denominacion + " | Año: " + str(self.modelo) + " | Patente: " + self.patente


class DocumentacionRodado (models.Model):
    #Esta clase representa la entrega de documentación del rodado
    rodado = models.ForeignKey(Rodado, on_delete=models.CASCADE)
    fecha = models.DateTimeField(blank=True, null=True)
    documentacion = models.ForeignKey(Documentacion, on_delete=models.CASCADE)


class GastoRodado (models.Model):
    rodado = models.ForeignKey(Rodado, on_delete=models.CASCADE)
    fecha = models.DateTimeField(blank=True, null=True)
    gasto = models.ForeignKey(Gasto, on_delete=models.CASCADE)
    montoGasto = models.FloatField()
    caja = models.ForeignKey(Caja, on_delete=models.SET_NULL, null=True, blank=True)
    numComprobante = models.CharField(max_length=100, blank=True, null=True)
    razonSocial = models.CharField(max_length=200, blank=True, null=True)
    fecha_record = models.DateField(auto_now_add=True, blank=True, null=True)
    user_record = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)



class Compra (models.Model):
    #Este modelo representa los datos de la compra de un rodado
    montoCompra = models.FloatField(blank=True, null=True)
    cotizacionDolar = models.FloatField(blank=True, null=True)
    fechaCompra = models.DateTimeField(blank=True, null=True)
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE)
    rodado=models.ForeignKey(Rodado, on_delete=models.CASCADE)

    fecha_record = models.DateField(auto_now_add=True, blank=True, null=True)
    user_record = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)


class Venta (models.Model):
    #Este modelo representa los datos generales de venta de un rodado
    #VER modelo financiacion
    montoVenta = models.FloatField(blank=True, null=True)
    cotizacionDolar = models.FloatField(blank=True, null=True)
    fechaVenta = models.DateTimeField(blank=True, null=True)
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE)
    rodado = models.ForeignKey(Rodado, on_delete=models.CASCADE)
    costoTransferencia = models.FloatField(blank=True, null=True)
    fecha_record = models.DateField(auto_now_add=True, blank=True, null=True)
    user_record = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

class CobranzaTransferencia(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.SET_NULL, null=True, blank=True)
    fechaCobranza = models.DateTimeField(blank=True, null=True)
    fecha_record = models.DateField(auto_now_add=True, blank=True, null=True)
    user_record = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)


class Transferencia (models.Model):
    fechaTransferencia = models.DateTimeField()
    rodado = models.ForeignKey(Rodado, on_delete=models.CASCADE)

    fecha_record = models.DateField(auto_now_add=True, blank=True, null=True)
    user_record = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

koe/templates/concesionaria/lista/caja.html
{%  extends 'concesionaria/lista/base_lista.html' %}

{% block titulo_lista %} Configuración - Cajas{% endblock %}

  {% block boton_superior %}
  <a class="btn btn-outline-success" href="{% url 'concesionaria:nuevo_gasto' %}">Agregar caja</a>
  {% endblock %}

{% block lista_contenido %}

<table id="listaGasto" class='table table-striped'>
  <thead>
    <tr>
      <td>#</td>
      <td>Denominación</td>
    </tr>
  </thead>
  <tbody id="tabla">
    <!-- Veo si hay registros de boleterías para mostrar-->
    {% if object_list %}
      {% for caja in object_list %}
        <tr>
          <td>{{caja.id}}</td>
          <td>{{caja.denominacion}}</td>
          <td>
            <div class="dropdown">
             <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
               Acciones
             </button>
             <div class="dropdown-menu">
                 <a class="dropdown-item" href="{% url 'concesionaria:editar_caja' caja.id %}">Editar</a>
            </div>

          </div>
          </td>
        </tr>
      {% endfor %}
    {% else %}
    <h1>No hay cajas registradas en el sistema</h1>
    <a class="btn btn-outline-success" href="{% url 'concesionaria:nueva_caja' %}">Agregar caja</a>
    {% endif %}
  </tbody>
</table>
{% endblock %}

koe/templates/concesionaria/lista/categoria.html
{%  extends 'concesionaria/lista/base_lista.html' %}

{% block titulo_lista %} Configuración - Categorías{% endblock %}


  {% block boton_superior %}
  <a class="btn btn-outline-success" href="{% url 'concesionaria:nueva_categoria' %}">Agregar categoría rodado</a>
  {% endblock %}

{% block lista_contenido %}

<table id="listaCategoria" class='table table-striped'>
  <thead>
    <tr>
      <td>#</td>
      <td>Denominación</td>
    </tr>
  </thead>
  <tbody id="tabla">
    <!-- Veo si hay registros de boleterías para mostrar-->
    {% if object_list %}
      {% for categoria in object_list %}
        <tr>
          <td>{{categoria.id}}</td>
          <td>{{categoria.denominacion}}</td>
          <td>
            <div class="dropdown">
             <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
               Acciones
             </button>
             <div class="dropdown-menu">
                 <a class="dropdown-item" href="{% url 'concesionaria:editar_categoria' categoria.id %}">Editar</a>
                 <a class="dropdown-item" href="{% url 'concesionaria:eliminar_categoria' categoria.id %}">Eliminar</a>
             </div>

          </div>
          </td>
        </tr>
      {% endfor %}
    {% else %}
    <h1>No hay categorías de rodados registradas en el sistema</h1>
    <a class="btn btn-outline-success" href="{% url 'concesionaria:nueva_categoria' %}">Agregar categoría rodado</a>
    {% endif %}
  </tbody>
</table>
{% endblock %}

koe/templates/concesionaria/lista/color.html
{%  extends 'concesionaria/lista/base_lista.html' %}

{% block titulo_lista %} Configuración - Colores{% endblock %}

  {% block boton_superior %}
  <a class="btn btn-outline-success" href="{% url 'concesionaria:nuevo_color' %}">Agregar color</a>
  {% endblock %}

{% block lista_contenido %}

<table id="listaColor" class='table table-striped'>
  <thead>
    <tr>
      <td>#</td>
      <td>Denominación</td>
    </tr>
  </thead>
  <tbody id="tabla">
    <!-- Veo si hay registros de boleterías para mostrar-->
    {% if object_list %}
      {% for color in object_list %}
        <tr>
          <td>{{color.id}}</td>
          <td>{{color.denominacion}}</td>
          <td>
            <div class="dropdown">
             <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
               Acciones
             </button>
             <div class="dropdown-menu">
                 <a class="dropdown-item" href="{% url 'concesionaria:editar_color' color.id %}">Editar</a>
                 <a class="dropdown-item" href="{% url 'concesionaria:eliminar_color' color.id %}">Eliminar</a>
             </div>

          </div>
          </td>
        </tr>
      {% endfor %}
    {% else %}
    <h1>No hay colores registrados en el sistema</h1>
    <a class="btn btn-outline-success" href="{% url 'concesionaria:nuevo_color' %}">Agregar color</a>
    {% endif %}
  </tbody>
</table>
{% endblock %}

koe/templates/concesionaria/lista/disponibles.html
{%  extends 'concesionaria/lista/base_lista.html' %}
{% load humanize %}
{% block titulo_lista %} Disponibles{% endblock %}

  {% block boton_superior %}
  <a class="btn btn-outline-success" href="{% url 'concesionaria:nuevo_rodado' %}">Agregar rodado</a>
  {% endblock %}

{% block lista_contenido %}
<table id="listaDisponibles" class='table table-striped'>
  <thead>
    <tr>
      <td>#</td>
      <td>Categoría</td>
      <td>Marca</td>
      <td>Denominación</td>
      <td>Año</td>
      <td>Patente</td>
      <td>Color</td>
      <td>Tiempo en stock</td>
    </tr>
  </thead>
  <tbody id="tabla">
    <!-- Veo si hay registros de boleterías para mostrar-->
    {% if disponibles %}
      {% for disponible in disponibles %}
        <tr>
          <td>{{disponible.rodado.id}}</td>
          <td>{{disponible.rodado.categoria.denominacion}}</td>
          <td>{{disponible.rodado.marca.denominacion}}</td>
          <td>{{disponible.rodado.denominacion}}</td>
          <td>{{disponible.rodado.modelo}}</td>
          <td>{{disponible.rodado.patente}}</td>
          <td>{{disponible.rodado.color}}</td>
          <td>{{disponible.fechaCompra|naturaltime}}</td>
          <td>
            <div class="dropdown">
             <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
               Acciones
             </button>
             <div class="dropdown-menu">
               <a class="dropdown-item" href="{% url 'concesionaria:estado_rodado' disponible.id %}">Estado</a>
             </div>

          </div>
          </td>
        </tr>
      {% endfor %}
    {% else %}
    <h1>No hay ventas registradas en el sistema</h1>
    <a class="btn btn-outline-success" href="{% url 'concesionaria:nueva_venta' %}">Agregar venta</a>
    {% endif %}
  </tbody>
</table>
{% endblock %}

koe/templates/concesionaria/lista/documentacion.html
{%  extends 'concesionaria/lista/base_lista.html' %}

{% block titulo_lista %} Configuración - Documentaciones{% endblock %}


  {% block boton_superior %}
  <a class="btn btn-outline-success" href="{% url 'concesionaria:nueva_documentacion' %}">Agregar documentación</a>
  {% endblock %}

{% block lista_contenido %}

<table id="listaDocumentacion" class='table table-striped'>
  <thead>
    <tr>
      <td>#</td>
      <td>Denominación</td>
      <td>Obligatorio</td>
    </tr>
  </thead>
  <tbody id="tabla">
    <!-- Veo si hay registros de boleterías para mostrar-->
    {% if object_list %}
      {% for documentacion in object_list %}
        <tr>
          <td>{{documentacion.id}}</td>
          <td>{{documentacion.denominacion}}</td>
          {% if documentacion.esObligatorio %}
            <td><i class="gg-check-r"></i></td>

          {% else %}
            <td></td>
          {% endif %}
          <td>
            <div class="dropdown">
             <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
               Acciones
             </button>
             <div class="dropdown-menu">
                 <a class="dropdown-item" href="{% url 'concesionaria:editar_documentacion' documentacion.id %}">Editar</a>
                 <a class="dropdown-item" href="{% url 'concesionaria:eliminar_documentacion' documentacion.id %}">Eliminar</a>
             </div>

          </div>
          </td>
        </tr>
      {% endfor %}
    {% else %}
    <h1>No hay documentaciones registradas en el sistema</h1>
    <a class="btn btn-outline-success" href="{% url 'concesionaria:nueva_documentacion' %}">Agregar documentación</a>
    {% endif %}
  </tbody>
</table>
{% endblock %}

koe/templates/concesionaria/lista/formapago.html
{%  extends 'concesionaria/lista/base_lista.html' %}

{% block titulo_lista %} Configuración - Formas de pago{% endblock %}

  {% block boton_superior %}
  <a class="btn btn-outline-success" href="{% url 'concesionaria:nueva_formapago' %}">Agregar forma de pago</a>
  {% endblock %}

{% block lista_contenido %}

<table id="listaFormaPago" class='table table-striped'>
  <thead>
    <tr>
      <td>#</td>
      <td>Denominación</td>
    </tr>
  </thead>
  <tbody id="tabla">
    <!-- Veo si hay registros de boleterías para mostrar-->
    {% if object_list %}
      {% for forma in object_list %}
        <tr>
          <td>{{forma.id}}</td>
          <td>{{forma.denominacion}}</td>
          <td>
            <div class="dropdown">
             <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
               Acciones
             </button>
             <div class="dropdown-menu">
                 <a class="dropdown-item" href="{% url 'concesionaria:editar_formapago' forma.id %}">Editar</a>
                 <a class="dropdown-item" href="{% url 'concesionaria:eliminar_formapago' forma.id %}">Eliminar</a>
             </div>

          </div>
          </td>
        </tr>
      {% endfor %}
    {% else %}
    <h1>No hay formas de pago registradas en el sistema</h1>
    <a class="btn btn-outline-success" href="{% url 'concesionaria:nueva_formapago' %}">Agregar forma de pago</a>
    {% endif %}
  </tbody>
</table>
{% endblock %}

koe/templates/concesionaria/lista/gasto.html
{%  extends 'concesionaria/lista/base_lista.html' %}

{% block titulo_lista %} Configuración - Conceptos de gastos{% endblock %}

  {% block boton_superior %}
  <a class="btn btn-outline-success" href="{% url 'concesionaria:nuevo_gasto' %}">Agregar gasto</a>
  {% endblock %}

{% block lista_contenido %}

<table id="listaGasto" class='table table-striped'>
  <thead>
    <tr>
      <td>#</td>
      <td>Denominación</td>
    </tr>
  </thead>
  <tbody id="tabla">
    <!-- Veo si hay registros de boleterías para mostrar-->
    {% if object_list %}
      {% for gasto in object_list %}
        <tr>
          <td>{{gasto.id}}</td>
          <td>{{gasto.denominacion}}</td>
          <td>
            <div class="dropdown">
             <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
               Acciones
             </button>
             <div class="dropdown-menu">
                 <a class="dropdown-item" href="{% url 'concesionaria:editar_gasto' gasto.id %}">Editar</a>
                 <a class="dropdown-item" href="{% url 'concesionaria:eliminar_gasto' gasto.id %}">Eliminar</a>
             </div>

          </div>
          </td>
        </tr>
      {% endfor %}
    {% else %}
    <h1>No hay conceptos de gastos registrados en el sistema</h1>
    <a class="btn btn-outline-success" href="{% url 'concesionaria:nuevo_gasto' %}">Agregar gasto</a>
    {% endif %}
  </tbody>
</table>
{% endblock %}